from __future__ import annotations

from app.modules.auth.domain.entities import (
    User,
    Tenant,
    UserSession,
    APIKey,
    Role,
    AuditLog,
    UserStatus,
    UserRole,
    Permission,
)
from app.modules.auth.domain.repositories import (
    UserRepository,
    TenantRepository,
    UserSessionRepository,
    APIKeyRepository,
    RoleRepository,
    AuditLogRepository,
)
from app.modules.auth.domain.events import (
    UserRegistered,
    UserLoggedIn,
    UserUpdated,
    UserDeleted,
    TenantCreated,
    TenantUpdated,
    TenantDeleted,
    SessionCreated,
    SessionRevoked,
    APIKeyCreated,
    APIKeyRevoked,
    MFARegistered,
    MFAVerified,
    MFADisabled,
    PasswordChanged,
    PasswordResetRequested,
    PasswordResetCompleted,
    EmailVerified,
)

__all__ = [
    "User",
    "Tenant",
    "UserSession",
    "APIKey",
    "Role",
    "AuditLog",
    "UserStatus",
    "UserRole",
    "Permission",
    "UserRepository",
    "TenantRepository",
    "UserSessionRepository",
    "APIKeyRepository",
    "RoleRepository",
    "AuditLogRepository",
    "UserRegistered",
    "UserLoggedIn",
    "UserUpdated",
    "UserDeleted",
    "TenantCreated",
    "TenantUpdated",
    "TenantDeleted",
    "SessionCreated",
    "SessionRevoked",
    "APIKeyCreated",
    "APIKeyRevoked",
    "MFARegistered",
    "MFAVerified",
    "MFADisabled",
    "PasswordChanged",
    "PasswordResetRequested",
    "PasswordResetCompleted",
    "EmailVerified",
]